#!/bin/bash
### BEGIN INIT INFO
# Provides:          packet-forwarder
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start packet-forwarder at boot time
# Description:       Start packet-forwarder at boot time
### END INIT INFO

# Start packet forwarder
function start {
    if [ ! -f /var/run/packet-forwarder.pid ]; then
        cd /opt/packet-forwarder
        ./basic_pkt_fwd > /dev/null 2>&1 &
        echo $! > /var/run/packet-forwarder.pid
    fi
}

# Stop packet forwarder
function stop {
    if [ -f /var/run/packet-forwarder.pid ]; then
        kill -TERM `cat /var/run/packet-forwarder.pid`
        rm /var/run/packet-forwarder.pid
    fi
}

# Switch case
case "$1" in 
    start)
        echo "Starting packet forwarder"
        start
        ;;
    restart)
        echo "Restarting packet forwarder"
        stop
        start
        ;;
    stop)
        echo "Stopping packet forwarder"
        stop
        ;;
    *)
        echo "Usage: /etc/init.d/packet-forwarder start|restart|stop"
        exit 1
        ;;
esac

exit 0
